version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DJANGO_ENV=development
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/recipe-app
    command: >
      sh -c "
             python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

volumes:
  dev-db-data: